export enum TokenSubject {
  APIKEY_ACCESS_TOKEN = 'APIKEY_ACCESS_TOKEN',
  USER_ACCESS_TOKEN = 'USER_ACCESS_TOKEN',
  USER_REFRESH_TOKEN = 'USER_REFRESH_TOKEN',
  APPROVE_EMAIL_TOKEN = 'APPROVE_EMAIL_TOKEN',
  APPROVE_SUBNET_TOKEN = 'APPROVE_SUBNET_TOKEN',
  EMAIL_MFA_TOKEN = 'EMAIL_MFA_TOKEN',
  MULTI_FACTOR_TOKEN = 'MULTI_FACTOR_TOKEN',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  MERGE_ACCOUNTS_TOKEN = 'MERGE_ACCOUNTS_TOKEN',
}
